### ISSUE TITLE
Demo Appeal

### ISSUE THREAD

**Issue by rglassett** [mvassilevsky/NationStatesClone#1]
NationStates can be interesting over the long term by having interesting issues that players can respond to every day or two; however, it doesn't have much going for it on the front-end and I don't think it would demo well.

I like the idea of fictional nations as a theme, though; I think it would work well with Google Maps integration (Yelp/AirBnB) or something like Kickstarter.

**Comment by mvassilevsky** [comment]
Regarding the slow pace of NationStates issues, I think that can be solved by having issues appear much more often, e.g. by having an "Apply Solutions" button on the Issues page that would enact the currently chosen issues and replace them with new ones. As for front-end stuff, I think having graphs that display the nation's various stats over time would look nice.
